#!/bin/bash

# Git
alias git="hub"
alias gp="git pull --rebase"
alias gl="git r"
alias gd="git diff"
alias gds="git diff --staged"
alias gr="git unpushed"
alias gc="git checkout"
alias gs="git status -sb"
alias gb="git branch"
alias ga="git add"
alias gwc='git whatchanged -p --abbrev-commit --pretty=medium'

# Ruby
alias testbot='bundle exec rake testbot:rspec 2>&1 | tee tmp/output.txt | grep "^\(Finished.*\.$\|rspec\|[0-9]\+ examples\)"'
alias s="spring"
alias b="bundle exec"
alias t="b rspec fast_spec/ && b rspec spec/ --order default"

# Misc
alias ll="ls -la"
alias flushdns='dscacheutil -flushcache'
alias redis-start="redis-server /usr/local/etc/redis.conf"
alias solr='cd ~/Code/solr && ./start.sh'
alias tlog='tail -f log/development.log'
