#!/bin/bash
WHITE="\[\033[0;38m\]"
RED="\[\033[0;31m\]"
BLUE="\[\033[0;34m\]"
PURPLE="\[\033[0;35m\]"
YELLOW="\[\033[0;33m\]"
GREEN="\[\033[0;32m\]"
CYAN="\[\033[0;36m\]"
NO_COLOUR="\[\033[0m\]"


# Git bransch on prompt
function git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null)
  if [ $ref ]; then
    echo " "${ref#refs/heads/}
  fi
}

DATE="$CYAN\$(date +%H:%M)"
SHORTPATH="$YELLOW\W"
GIT_BRANCH="$CYAN\$(git_branch)"

export PS1="$DATE $SHORTPATH$GIT_BRANCH$NO_COLOUR "
